pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'
  demands: sh

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.8'
  inputs:
    versionSpec: 3.8

- bash: |
    pip install .[azure,dev]
  displayName: 'Install Requirements'

- bash: |
    flake8
  displayName: 'Lint the code'

- bash: |
    coverage run --source=src -m pytest --junitxml=junit/test-results.xml
    coverage html
    coverage xml
  displayName: 'Test the code with coverage'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'junit/test-*.xml'
    testRunTitle: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: './coverage.xml'
    reportDirectory: './htmlcov'

